### ISSUE TITLE
Forbidden 403

### ISSUE THREAD

**Issue by petr-henys** [biomedisa/biomedisa#4]
Hi,
i cannot upload image file in Biomedisa online app. The server complains:
CSRF verification failed. Request aborted.

It worked before, but last couple of days i have been unable to upload files for segmentation. The image has around 73Mb and cannot be uploaded, but if i try another file with much smaller size (a few Kbs) it works. What am I doing wrong?

thanks,
Petr

**Comment by biomedisa** [comment]
Hi Petr,
thanks for your comment! We had some memory issues, could you please try again. The app should now work properly again. I am sorry for the inconvenience.
Best wishes,
Philipp
