### ISSUE TITLE
Problems when installing biomedisa 

### ISSUE THREAD

**Issue by Myriamouk** [biomedisa/biomedisa#7]
Hello Mr Lösel,
First, I would like to thank you for having developed this super tool !

We tried with my lab's IT department to carry out 2 installation modes from the Github, the first on a shared computer, the second on my office computer.

For the first installation we followed the Windows 10 + CUDA + GPU (command-line-only) protocol. We had difficulties when modifying the path. Would it be possible to detail this step in more detail in your documentation?

For the second installation, we followed the Windows 10 + OpenCL + CPU (command-line-only) protocol. It is not noted in this installation protocol that it is necessary to install Microsoft Visual Studio although it displays errors if it is not installed.
There is also a problem with the new version of OpenCL (2024) and there is no solution currently offered to my knowledge. For this I don't know how this could be arranged, apart from indicating it in info on the Github?

Thanks again,

Myriam

**Comment by biomedisa** [comment]
Hi Myriam,
Thank you for your feedback!
> We had difficulties when modifying the path. Would it be possible to detail this step in more detail in your documentation?

I will create an installation video that explains the installation on Windows step by step and provides more details on how to set up the path variable. This seems to be a big problem and many people have problems with this point.

> For the second installation, we followed the Windows 10 + OpenCL + CPU (command-line-only) protocol. It is not noted in this installation protocol that it is necessary to install Microsoft Visual Studio although it displays errors if it is not installed.

I added it to the installation protocol.

> There is also a problem with the new version of OpenCL (2024) and there is no solution currently offered to my knowledge. For this I don't know how this could be arranged, apart from indicating it in info on the GitHub?

Thank you for this hint. The installation protocol for Windows and CPUs is expected to be discontinued. It is quite difficult to maintain multiple options and CPUs have the least importance. In the long term, Biomedisa support for Windows will be via WSL, which will allow the use of the same installation protocol as for Ubuntu (with the exception of installing WSL). This makes development and testing easier and should allow me to support different options on both platforms.

Cheers,
Philipp

**Comment by biomedisa** [comment]
Here is a [YouTube tutorial](https://www.youtube.com/watch?v=Ia4cMBDJXrI) that explains how to modify the path variable in more detail.

**Comment by Myriamouk** [comment]
Thank you for providing this tutorial.

Cheers,
Myriam
